# Generated by Django 2.2.8 on 2020-01-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20200106_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to='prof_pics'),
        ),
    ]
